#! /bin/sh
# Copyright (c) 2006 Peter Denno
#
# Author: peter.denno@nist.gov based on adrian@suse.de slpd, based on template 
# from source package, which is Copyright (c) 2003 SuSE AG Nuernberg, Germany.
#
#
### BEGIN INIT INFO
# Provides:          sei
# Required-Start:    $network $apache2
# Required-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 4 6
# Description: Server for SEI -- SE Interop project
### END INIT INFO

. /etc/rc.status

# Determine the base and follow a runlevel link name.
base=${0##*/}
link=${base#*[SK][0-9][0-9]}
sei=/home/pdenno/projects/sei/source/sei.exe

# Force execution if not called by a runlevel directory.
test -x $sei || exit 0

case "$1" in
  start)
    echo -n 'Starting sei '
    startproc -u pdenno $sei
    rc_status -v
    ;;
  stop)
    echo -n "Shutting down sei "
    killproc -TERM $sei
    rc_status -v
    ;;
  restart)
    $0 stop
    $0 start
    rc_status
    ;;
  try-restart)
    $0 status
    if test $? = 0; then
	$0 restart
    else
	rc_reset
    fi
    rc_status
    ;;
  force-reload)
    $0 stop; sleep 1  &&  $0 start
    rc_status
    ;;
  reload)
    echo -n "Reload service sei "
    killproc -HUP $sei
    rc_status -v
    ;;
  status)
    echo -n "Checking for sei "
    checkproc $sei
    rc_status -v
    ;;
  *)
    echo "Usage: $0 {start|stop|try-restart|restart|force-reload|reload|status}"
    exit 1
esac
rc_exit
